export const ALL_DISEASE_REQUEST = 'ALL_DISEASE_REQUEST'
export const ALL_DISEASE_SUCCESS = 'ALL_DISEASE_SUCCESS'
export const ALL_DISEASE_FAIL = 'ALL_DISEASE_FAIL'


export const DISEASE_DETAILS_REQUEST = 'DISEASE_DETAILS_REQUEST'
export const DISEASE_DETAILS_SUCCESS = 'DISEASE_DETAILS_SUCCESS'
export const DISEASE_DETAILS_FAIL = 'DISEASE_DETAILS_FAIL'


export const NEW_DISEASE_REQUEST = 'NEW_DISEASE_REQUEST'
export const NEW_DISEASE_SUCCESS = 'NEW_DISEASE_SUCCESS'
export const NEW_DISEASE_FAIL = 'NEW_DISEASE_FAIL'
export const NEW_DISEASE_RESET = 'NEW_DISEASE_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'