export const ALL_HOSPITAL_REQUEST = 'ALL_HOSPITAL_REQUEST'
export const ALL_HOSPITAL_SUCCESS = 'ALL_HOSPITAL_SUCCESS'
export const ALL_HOSPITAL_FAIL = 'ALL_HOSPITAL_FAIL'


export const HOSPITAL_DETAILS_REQUEST = 'HOSPITAL_DETAILS_REQUEST'
export const HOSPITAL_DETAILS_SUCCESS = 'HOSPITAL_DETAILS_SUCCESS'
export const HOSPITAL_DETAILS_FAIL = 'HOSPITAL_DETAILS_FAIL'
export const HOSPITAL_BYID_REQUEST = 'HOSPITAL_BYID_REQUEST'
export const HOSPITAL_BYID_SUCCESS = 'HOSPITAL_BYID_SUCCESS'
export const HOSPITAL_BYID_FAIL = 'HOSPITAL_BYID_FAIL'


export const NEW_HOSPITAL_REQUEST = 'NEW_HOSPITAL_REQUEST'
export const NEW_HOSPITAL_SUCCESS = 'NEW_HOSPITAL_SUCCESS'
export const NEW_HOSPITAL_FAIL = 'NEW_HOSPITAL_FAIL'
export const NEW_HOSPITAL_RESET = 'NEW_HOSPITAL_RESET'


export const UPDATE_HOSPITAL_REQUEST = 'UPDATE_HOSPITAL_REQUEST'
export const UPDATE_HOSPITAL_SUCCESS = 'UPDATE_HOSPITAL_SUCCESS'
export const UPDATE_HOSPITAL_FAIL = 'UPDATE_HOSPITAL_FAIL'
export const UPDATE_HOSPITAL_RESET = 'UPDATE_HOSPITAL_RESET'


export const DELETE_HOSPITAL_REQUEST = 'DELETE_HOSPITAL_REQUEST'
export const DELETE_HOSPITAL_SUCCESS = 'DELETE_HOSPITAL_SUCCESS'
export const DELETE_HOSPITAL_FAIL = 'DELETE_HOSPITAL_FAIL'
export const DELETE_HOSPITAL_RESET = 'DELETE_HOSPITAL_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'