export const ALL_LAB_REQUEST = 'ALL_LAB_REQUEST'
export const ALL_LAB_SUCCESS = 'ALL_LAB_SUCCESS'
export const ALL_LAB_FAIL = 'ALL_LAB_FAIL'


export const LAB_DETAILS_REQUEST = 'LAB_DETAILS_REQUEST'
export const LAB_DETAILS_SUCCESS = 'LAB_DETAILS_SUCCESS'
export const LAB_DETAILS_FAIL = 'LAB_DETAILS_FAIL'


export const NEW_LAB_REQUEST = 'NEW_LAB_REQUEST'
export const NEW_LAB_SUCCESS = 'NEW_LAB_SUCCESS'
export const NEW_LAB_FAIL = 'NEW_LAB_FAIL'
export const NEW_LAB_RESET = 'NEW_LAB_RESET'
// 

export const UPDATE_LAB_REQUEST = 'UPDATE_LAB_REQUEST'
export const UPDATE_LAB_SUCCESS = 'UPDATE_LAB_SUCCESS'
export const UPDATE_LAB_FAIL = 'UPDATE_LAB_FAIL'
export const UPDATE_LAB_RESET = 'UPDATE_LAB_RESET'


export const DELETE_LAB_REQUEST = 'DELETE_LAB_REQUEST'
export const DELETE_LAB_SUCCESS = 'DELETE_LAB_SUCCESS'
export const DELETE_LAB_FAIL = 'DELETE_LAB_FAIL'
export const DELETE_LAB_RESET = 'DELETE_LAB_RESET'


export const LAB_SEARCH_REQUEST = 'LAB_SEARCH_REQUEST';
export const LAB_SEARCH_SUCCESS = 'LAB_SEARCH_SUCCESS';
export const LAB_SEARCH_FAIL = 'LAB_SEARCH_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS'