export const ALL_SYMPTOM_REQUEST = 'ALL_SYMPTOM_REQUEST'
export const ALL_SYMPTOM_SUCCESS = 'ALL_SYMPTOM_SUCCESS'
export const ALL_SYMPTOM_FAIL = 'ALL_SYMPTOM_FAIL'


export const SYMPTOM_DETAILS_REQUEST = 'SYMPTOM_DETAILS_REQUEST'
export const SYMPTOM_DETAILS_SUCCESS = 'SYMPTOM_DETAILS_SUCCESS'
export const SYMPTOM_DETAILS_FAIL = 'SYMPTOM_DETAILS_FAIL'


export const NEW_SYMPTOM_REQUEST = 'NEW_SYMPTOM_REQUEST'
export const NEW_SYMPTOM_SUCCESS = 'NEW_SYMPTOM_SUCCESS'
export const NEW_SYMPTOM_FAIL = 'NEW_SYMPTOM_FAIL'
export const NEW_SYMPTOM_RESET = 'NEW_SYMPTOM_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'