export const ALL_DOCTORAPPOINTMENT_REQUEST = 'ALL_DOCTORAPPOINTMENT_REQUEST'
export const ALL_DOCTORAPPOINTMENT_SUCCESS = 'ALL_DOCTORAPPOINTMENT_SUCCESS'
export const ALL_DOCTORAPPOINTMENT_FAIL = 'ALL_DOCTORAPPOINTMENT_FAIL'


export const NEW_DOCTORAPPOINTMENT_REQUEST = 'NEW_DOCTORAPPOINTMENT_REQUEST'
export const NEW_DOCTORAPPOINTMENT_SUCCESS = 'NEW_DOCTORAPPOINTMENT_SUCCESS'
export const NEW_DOCTORAPPOINTMENT_FAIL = 'NEW_DOCTORAPPOINTMENT_FAIL'
export const NEW_DOCTORAPPOINTMENT_RESET = 'NEW_DOCTORAPPOINTMENT_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'