export const ALL_SURGEONAPPOINTMENT_REQUEST = 'ALL_SURGEONAPPOINTMENT_REQUEST'
export const ALL_SURGEONAPPOINTMENT_SUCCESS = 'ALL_SURGEONAPPOINTMENT_SUCCESS'
export const ALL_SURGEONAPPOINTMENT_FAIL = 'ALL_SURGEONAPPOINTMENT_FAIL'


export const NEW_SURGEONAPPOINTMENT_REQUEST = 'NEW_SURGEONAPPOINTMENT_REQUEST'
export const NEW_SURGEONAPPOINTMENT_SUCCESS = 'NEW_SURGEONAPPOINTMENT_SUCCESS'
export const NEW_SURGEONAPPOINTMENT_FAIL = 'NEW_SURGEONAPPOINTMENT_FAIL'
export const NEW_SURGEONAPPOINTMENT_RESET = 'NEW_SURGEONAPPOINTMENT_RESET'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'